language: node_js
node_js:
  - stable

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

before_script:
  - npm install -g firebase-tools

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive -m "This site is being hosted from the development branch."
  - npm run clean

notifications:
  email:
    on_failure: change
    on_success: change
